
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Phuong Anh Hoang
 */
public class frmQuanLy extends javax.swing.JFrame {

    private String taiKhoan = "";

    public String getTaiKhoan() {
        return taiKhoan;
    }

    public void setTaiKhoan(String taiKhoan) {
        this.taiKhoan = taiKhoan;
    }
    
    private enum Status{TAI_KHOAN, KHONG_CO, TAT_CA};
    
    /**
     * Creates new form frmQuanLy
     */
    public frmQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNguoiDung = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTuKhoa = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        rbtnCuMoi = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtnAZ = new javax.swing.JRadioButton();
        rbtnSoDu = new javax.swing.JRadioButton();
        btnThoat = new javax.swing.JButton();
        btnMatKhau = new javax.swing.JButton();
        btnLichSu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 240, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableNguoiDung.setBackground(new java.awt.Color(255, 240, 240));
        jTableNguoiDung.setForeground(new java.awt.Color(51, 0, 102));
        jTableNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableNguoiDung);

        jPanel1.setBackground(new java.awt.Color(255, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Tài khoản:");

        lblTaiKhoan.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(51, 0, 102));

        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Tìm kiếm theo tên hoặc số tài khoản:");

        txtTuKhoa.setForeground(new java.awt.Color(51, 0, 102));

        btnTim.setBackground(new java.awt.Color(255, 200, 210));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search icon.png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnCuMoi);
        rbtnCuMoi.setForeground(new java.awt.Color(51, 0, 102));
        rbtnCuMoi.setText("Theo nhóm");
        rbtnCuMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCuMoiActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Sắp xếp danh sách:");

        buttonGroup1.add(rbtnAZ);
        rbtnAZ.setForeground(new java.awt.Color(51, 0, 102));
        rbtnAZ.setText("A => Z");
        rbtnAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAZActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnSoDu);
        rbtnSoDu.setForeground(new java.awt.Color(51, 0, 102));
        rbtnSoDu.setText("Số dư giảm dần");
        rbtnSoDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSoDuActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 200, 210));
        btnThoat.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnMatKhau.setBackground(new java.awt.Color(255, 200, 210));
        btnMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pass2.png"))); // NOI18N
        btnMatKhau.setMaximumSize(new java.awt.Dimension(70, 70));
        btnMatKhau.setMinimumSize(new java.awt.Dimension(70, 70));
        btnMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatKhauActionPerformed(evt);
            }
        });

        btnLichSu.setBackground(new java.awt.Color(255, 200, 210));
        btnLichSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TransactionHistory.png"))); // NOI18N
        btnLichSu.setMaximumSize(new java.awt.Dimension(70, 70));
        btnLichSu.setMinimumSize(new java.awt.Dimension(70, 70));
        btnLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnCuMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnAZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnSoDu)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLichSu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(btnLichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTim)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtnCuMoi)
                    .addComponent(rbtnAZ)
                    .addComponent(rbtnSoDu))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 240, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));

        btnThem.setBackground(new java.awt.Color(255, 200, 210));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 200, 210));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 200, 210));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(948, 948, 948))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("Administration panel");
        
        QuanLy objQL = DataProvider.getQuanLyBus().layChiTietQuanLy(taiKhoan);
        
        lblTaiKhoan.setText(objQL.getHoTen());
        
        hienThiDanhSachNguoiDung();
    }//GEN-LAST:event_formWindowOpened

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        hienThiDanhSachNguoiDung();
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        frmThemNguoiDung frmAdd = new frmThemNguoiDung();
        frmAdd.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int dongChon = jTableNguoiDung.getSelectedRow();
        String soTaiKhoan = "" + jTableNguoiDung.getValueAt(dongChon, 0);
        
        frmThemNguoiDung frmUpdate = new frmThemNguoiDung();
        frmUpdate.setStk(soTaiKhoan);
        frmUpdate.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete this account?", "Alert!",
                JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        
        if(ketQua == JOptionPane.YES_OPTION)
        {
            int dongChon = jTableNguoiDung.getSelectedRow();
            String stk = "" + jTableNguoiDung.getValueAt(dongChon, 0);
        
            //Gọi hàm xóa
            boolean kq = DataProvider.getNguoiDungBus().xoaNguoiDung(stk);
            
            if(kq)
            {
                JOptionPane.showMessageDialog(rootPane, "Account is successfully deleted");
                hienThiDanhSachNguoiDung();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void rbtnCuMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCuMoiActionPerformed
        List<NguoiDung> lstNguoiDungTheoNhom = DataProvider.getNguoiDungBus().layDanhSach()
                .stream().sorted(Comparator.comparing(NguoiDung::getTaiKhoan))
                .collect(Collectors.toList());
        
        DanhSachNguoiDung(lstNguoiDungTheoNhom);
    }//GEN-LAST:event_rbtnCuMoiActionPerformed

    private void rbtnAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAZActionPerformed
        List<NguoiDung> lstNguoiDungAZ = DataProvider.getNguoiDungBus().layDanhSach()
                .stream().sorted(Comparator.comparing(NguoiDung::getHoTen))
                .collect(Collectors.toList());
        
        DanhSachNguoiDung(lstNguoiDungAZ);
    }//GEN-LAST:event_rbtnAZActionPerformed

    private void rbtnSoDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSoDuActionPerformed
        List<NguoiDung> lstNguoiDungSoDu = DataProvider.getNguoiDungBus().layDanhSach()
                .stream().sorted(Comparator.comparing(NguoiDung::getSoDu).reversed())
                .collect(Collectors.toList());
        
        DanhSachNguoiDung(lstNguoiDungSoDu);
    }//GEN-LAST:event_rbtnSoDuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "Are you sure to exit?", "Attention!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(ketQua == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatKhauActionPerformed
        frmMatKhau frmPass = new frmMatKhau();
        frmPass.setTaiKhoan(taiKhoan);
        frmPass.setVisible(true);
    }//GEN-LAST:event_btnMatKhauActionPerformed

    private void btnLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuActionPerformed
        int dongChon = jTableNguoiDung.getSelectedRow();
        String soTaiKhoan = "";
        boolean ketQua = false;
        Status trangThai = Status.KHONG_CO;
        
        if(dongChon >= 0){
            soTaiKhoan = "" + jTableNguoiDung.getValueAt(dongChon, 0);
        }
        
        List<SaoKe> lstGiaoDich = DataProvider.getGiaoDichBus().docGiaoDich(soTaiKhoan);
        
        if(!lstGiaoDich.isEmpty()){
            trangThai = Status.TAI_KHOAN;
        }
        
        if(dongChon == -1){
            trangThai = Status.TAT_CA;
        }
        
        switch(trangThai){
            case KHONG_CO:{
                JOptionPane.showMessageDialog(rootPane, "This account does not have any transactions!");
                break;
            }
            case TAI_KHOAN:
            case TAT_CA:{
            frmLichSuGiaoDich frmHistory = new frmLichSuGiaoDich();
            frmHistory.setStk(soTaiKhoan);
            frmHistory.setVisible(true);     
            }
        }
    }//GEN-LAST:event_btnLichSuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLichSu;
    private javax.swing.JButton btnMatKhau;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableNguoiDung;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JRadioButton rbtnAZ;
    private javax.swing.JRadioButton rbtnCuMoi;
    private javax.swing.JRadioButton rbtnSoDu;
    private static javax.swing.JTextField txtTuKhoa;
    // End of variables declaration//GEN-END:variables

    public static void hienThiDanhSachNguoiDung() {
        String tuKhoa = "";
        tuKhoa = txtTuKhoa.getText();
        
        String[] tieuDe = new String[]{"Số tài khoản", "Họ tên", "Mật khẩu", "Ngày sinh", "Giới tinh", "Điện thoại", "Email", "Địa chỉ", "Số dư", "Mã tài khoản"};
        
        NguoiDungBusiness nguoiDungBusiness = new NguoiDungBusiness();
        
        List<NguoiDung> lstNguoiDung = DataProvider.getNguoiDungBus().timKiem(tuKhoa);
        
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        
        Object row[];
        
        for(NguoiDung nd : lstNguoiDung){
            row = new Object[10];
            row[0] = nd.getSoTaiKhoan();
            row[1] = nd.getHoTen();
            row[2] = nd.getMatKhau();
            row[3] = nd.getNgaySinh();
            row[4] = nd.getGioiTinh();
            row[5] = nd.getDienThoai();
            row[6] = nd.getEmail();
            row[7] = nd.getDiaChi();
            row[8] = nd.getSoDu();
            row[9] = nd.getTaiKhoan();
            
            model.addRow(row);
        }
        
        jTableNguoiDung.setModel(model);
    }
    
    private void DanhSachNguoiDung(List<NguoiDung> lst) {
        
        NguoiDungBusiness nguoiDungBusiness = new NguoiDungBusiness();
        
        String[] tieuDe = new String[]{"Số tài khoản", "Họ tên", "Mật khẩu", "Ngày sinh", "Giới tinh", "Điện thoại", "Email", "Địa chỉ", "Số dư", "Tài khoản"};
        
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        
        Object row[];
        
        for(NguoiDung nd : lst){
            row = new Object[10];
            row[0] = nd.getSoTaiKhoan();
            row[1] = nd.getHoTen();
            row[2] = nd.getMatKhau();
            row[3] = nd.getNgaySinh();
            row[4] = nd.getGioiTinh();
            row[5] = nd.getDienThoai();
            row[6] = nd.getEmail();
            row[7] = nd.getDiaChi();
            row[8] = nd.getSoDu();
            row[9] = nd.getTaiKhoan();
            
            model.addRow(row);
        }
        
        jTableNguoiDung.setModel(model);
    }
}
