
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Phuong Anh Hoang
 */
public class frmThemNguoiDung extends javax.swing.JFrame {

    private String stk = "";

    public String getStk() {
        return stk;
    }

    public void setStk(String stk) {
        this.stk = stk;
    }
    
    private enum Status{THONG_TIN, NUT, TIEP_TUC, MAT_KHAU, TAI_KHOAN};
    
    /**
     * Creates new form frmThemNguoiDung
     */
    public frmThemNguoiDung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        txtSoTaiKhoan = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jDateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        txtDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDu = new javax.swing.JTextField();
        cboTaiKhoan = new javax.swing.JComboBox<>();
        btnHuyBo = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin người dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 0, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 0, 102));

        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Số tài khoản:");

        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Họ tên:");

        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Mật khẩu:");

        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("Ngày sinh:");

        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("Giới tính:");

        jLabel6.setForeground(new java.awt.Color(51, 0, 102));
        jLabel6.setText("Điện thoại:");

        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("Email:");

        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("Địa chỉ:");

        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("Số dư:");

        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("Tài khoản:");

        buttonGroupGioiTinh.add(rbtnNam);
        rbtnNam.setForeground(new java.awt.Color(51, 0, 102));
        rbtnNam.setText("Nam");

        buttonGroupGioiTinh.add(rbtnNu);
        rbtnNu.setForeground(new java.awt.Color(51, 0, 102));
        rbtnNu.setText("Nữ");

        txtSoTaiKhoan.setForeground(new java.awt.Color(51, 0, 102));
        txtSoTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoTaiKhoanKeyPressed(evt);
            }
        });

        txtHoTen.setForeground(new java.awt.Color(51, 0, 102));
        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoTenKeyPressed(evt);
            }
        });

        txtMatKhau.setForeground(new java.awt.Color(51, 0, 102));
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });

        jDateChooserNgaySinh.setForeground(new java.awt.Color(51, 0, 102));

        txtDienThoai.setForeground(new java.awt.Color(51, 0, 102));
        txtDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDienThoaiKeyPressed(evt);
            }
        });

        txtEmail.setForeground(new java.awt.Color(51, 0, 102));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        txtDiaChi.setForeground(new java.awt.Color(51, 0, 102));
        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyPressed(evt);
            }
        });

        txtSoDu.setForeground(new java.awt.Color(51, 0, 102));

        cboTaiKhoan.setForeground(new java.awt.Color(51, 0, 102));
        cboTaiKhoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "VIP", "Lâu năm" }));

        btnHuyBo.setBackground(new java.awt.Color(255, 200, 210));
        btnHuyBo.setForeground(new java.awt.Color(51, 0, 102));
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel icon.png"))); // NOI18N
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 200, 210));
        btnCapNhat.setForeground(new java.awt.Color(51, 0, 102));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK.png"))); // NOI18N
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboTaiKhoan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnNu))
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(167, 167, 167)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtDienThoai))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(txtSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbtnNam)
                            .addComponent(rbtnNu)
                            .addComponent(jLabel6)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cboTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat)
                    .addComponent(btnHuyBo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        hienThiTaiKhoan();
        
        if(stk.isEmpty()){
            this.setTitle("Add user");
        }else{
            this.setTitle("Update user");
            hienThiThongTinND();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        
        boolean ketQua = false;
        
        Status trangThai = Status.TIEP_TUC;
        List<NguoiDung> lstSTK = DataProvider.getNguoiDungBus().layDanhSach();
        
        if(txtSoTaiKhoan.getText().length() != 10){
            trangThai = Status.TAI_KHOAN;
        }
        if(txtMatKhau.getText().length() != 4){
            trangThai = Status.MAT_KHAU;
        }
        
        if(txtSoTaiKhoan.getText().isEmpty() || txtHoTen.getText().isEmpty() || txtMatKhau.getText().isEmpty() ||
                txtDienThoai.getText().isEmpty() || txtEmail.getText().isEmpty() ||
                txtDiaChi.getText().isEmpty() || txtSoDu.getText().isEmpty()){
            trangThai = Status.THONG_TIN;
        }
        
        if(!rbtnNam.isSelected() && !rbtnNu.isSelected()){
                trangThai = Status.NUT;
        }  
        
        switch(trangThai){
            case THONG_TIN:{
                JOptionPane.showMessageDialog(rootPane, "Please fill in all information of the form!");
                break;
            }
            case NUT:{
                JOptionPane.showMessageDialog(rootPane, "Please select your gender!");
                break;
            }
            case TAI_KHOAN:{
                JOptionPane.showMessageDialog(rootPane, "Account number includes 10 characters! Please enter valid account number!");
                break;
            }
            case MAT_KHAU:{
                JOptionPane.showMessageDialog(rootPane, "Password includes 4 characters! Please enter valid password!");
                break;
            }
            case TIEP_TUC:{
                String taiKhoan = "";
                NguoiDung objND = new NguoiDung();
        
                objND.setSoTaiKhoan(txtSoTaiKhoan.getText());
                objND.setHoTen(txtHoTen.getText());
                objND.setMatKhau(txtMatKhau.getText());

                objND.setNgaySinh((Date) jDateChooserNgaySinh.getDate());

                if(rbtnNam.isSelected()){
                    objND.setGioiTinh("Nam");
                }else{
                    objND.setGioiTinh("Nữ");
                }

                objND.setDienThoai(txtDienThoai.getText());
                objND.setEmail(txtEmail.getText());
                objND.setDiaChi(txtDiaChi.getText());
                objND.setSoDu(Double.parseDouble(txtSoDu.getText()));
                TaiKhoan objTK = (TaiKhoan)cboTaiKhoan.getSelectedItem();
                
                if(objTK != null){
                    taiKhoan = objTK.getMaTaiKhoan();
                }
                
                objND.setTaiKhoan(taiKhoan);
                boolean thucHien = true;
                
                if(!stk.isEmpty()){
                    ketQua = DataProvider.getNguoiDungBus().suaNguoiDung(objND);
                }else{
                    for(int i = 0; i < lstSTK.size(); i++){
                        if(txtSoTaiKhoan.getText().equals(lstSTK.get(i).getSoTaiKhoan())){
                            thucHien = false;
                        }
                    }
                if(thucHien){
                    ketQua = DataProvider.getNguoiDungBus().themNguoiDung(objND);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Account number already exists! Please enter valid account number!");
                }
            }
        }
        
        if(ketQua){
                JOptionPane.showMessageDialog(rootPane, "Successfully updated user information");

                frmQuanLy.hienThiDanhSachNguoiDung();

                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtSoTaiKhoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTaiKhoanKeyPressed
        int key = evt.getKeyCode();
        if(key == 10 || key == 9){
            txtHoTen.requestFocus();
        }
    }//GEN-LAST:event_txtSoTaiKhoanKeyPressed

    private void txtHoTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyPressed
        int key = evt.getKeyCode();
        if(key == 10 || key == 9){
            txtMatKhau.requestFocus();
        }
    }//GEN-LAST:event_txtHoTenKeyPressed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        int key = evt.getKeyCode();
        if(key == 10 || key == 9){
            txtDienThoai.requestFocus();
        }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void txtDienThoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDienThoaiKeyPressed
        int key = evt.getKeyCode();
        if(key == 10 || key == 9){
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtDienThoaiKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        int key = evt.getKeyCode();
        if(key == 10 || key == 9){
            txtDiaChi.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtDiaChiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyPressed
        int key = evt.getKeyCode();
        if(key == 10 || key == 9){
            txtSoDu.requestFocus();
        }
    }//GEN-LAST:event_txtDiaChiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThemNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThemNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThemNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThemNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThemNguoiDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.ButtonGroup buttonGroupGioiTinh;
    private javax.swing.JComboBox<String> cboTaiKhoan;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSoDu;
    private javax.swing.JTextField txtSoTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void hienThiTaiKhoan(){
        TaiKhoanBusiness taiKhoan = new TaiKhoanBusiness();
        
        List<TaiKhoan> lstTaiKhoan = DataProvider.getTaiKhoanBus().layDanhSach();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for(TaiKhoan tk : lstTaiKhoan){
            model.addElement(tk);
        }
        
        cboTaiKhoan.setRenderer(new TaiKhoanRender());
        cboTaiKhoan.setModel(model);
    }
    private void hienThiThongTinND() {
        NguoiDung objND = DataProvider.getNguoiDungBus().layChiTietNguoiDung(stk);
        if(objND != null){
            txtSoTaiKhoan.setText(stk);
            txtSoTaiKhoan.setEnabled(false);
            
            txtHoTen.setText(objND.getHoTen());
            txtMatKhau.setText(objND.getMatKhau());
            
            jDateChooserNgaySinh.setDate(objND.getNgaySinh());
            
            if(objND.getGioiTinh().equals("Nam")){
                rbtnNam.setSelected(true);
            }else{
                rbtnNu.setSelected(true);
            }
            
            txtDienThoai.setText(objND.getDienThoai());
            txtEmail.setText(objND.getEmail());
            txtDiaChi.setText(objND.getDiaChi());
            txtSoDu.setText(Double.toString(objND.getSoDu()));
            
            TaiKhoanBusiness taiKhoanBusiness = new TaiKhoanBusiness();
            TaiKhoan objTK = taiKhoanBusiness.layChiTietTaiKhoan(objND.getTaiKhoan());
            if(objTK != null){
                cboTaiKhoan.getModel().setSelectedItem(objTK);
            }
            
        }
    }
}
